apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sigaplus
  name: sigaplus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigaplus
  template:
    metadata:
      labels:
        app: sigaplus
    spec:
      containers:
      - image: sagr2003/sigaplus:{{ .Values.env.APP_VERSION }}
        name: sigaplus
        ports:
        - containerPort: 8081
        resources: 
          requests:
            cpu: "100m"
            memory: "400Mi"
          limits:
            cpu: "200m"
            memory: "600Mi"
